apiVersion: batch/v1
kind: Job
metadata:
  name: build-website-job
spec:
  template:
    spec:
      containers:
      - name: build-website-container
        image: ubuntu:20.04
        command: ["/bin/bash", "-c"]
        args: ["cat /config/build-script.sh | bash"]
        volumeMounts:
        - name: config-volume
          mountPath: /config
      restartPolicy: Never
      volumes:
      - name: config-volume
        configMap:
          name: website-configmap
