apiVersion: v1
kind: ConfigMap
metadata:
  name: website-configmap
data:
  build-script.sh: |
    #!/bin/bash
    apt-get update
    apt-get install -y git make curl
    git clone https://github.com/chazapis/hy548.git
    cd hy548
    git submodule update --init --recursive
    apt-get update
    curl -LO https://github.com/gohugoio/hugo/releases/download/v0.96.0/hugo_extended_0.96.0_Linux-64bit.tar.gz
    tar -xf hugo_extended_0.96.0_Linux-64bit.tar.gz
    mv hugo /usr/local/bin/
    make
